# Generated by Django 5.0.4 on 2024-04-22 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='saldo',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='foto',
            field=models.ImageField(blank=True, default='fotos_perfil/default.jpg', null=True, upload_to='fotos_perfil/'),
        ),
    ]
